add_newline = true
format = "$all"
[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"
format = "[$symbol$percentage]($style)"
[[battery.display]]
threshold = 30
style = "bold red"
[cmd_duration]
min_time = 100
[git_branch]
symbol = "ğŸŒ³ "
